<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="MFAC_Test" tests="33" failures="18" timestamp="04 Jan 2019 19:58:47 GMT" time="47.828" errors="0">
  <testcase name="SetEvironmentLevel" time="0.012" classname="SupportClasses.Set_Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="IssuePin" time="1.883" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;pinOTP&amp;quot; and a string containing &amp;quot;pinExpirationDate&amp;quot;)
     but: a string containing &amp;quot;pinOTP&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;e893f324-8bcf-4fb9-932e-87f227a0ca9d&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"e893f324-8bcf-4fb9-932e-87f227a0ca9d","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePin(MFAC.java:147)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- IssuePin -->
  <testcase name="IssuePin" time="2.539" classname="MFAC.MFAC"/>
  <testcase name="IssuePin" time="3.614" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;pinOTP&amp;quot; and a string containing &amp;quot;pinExpirationDate&amp;quot;)
     but: a string containing &amp;quot;pinOTP&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;55a4af70-1d59-4c1f-a720-bb244fa9d33a&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"55a4af70-1d59-4c1f-a720-bb244fa9d33a","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePin(MFAC.java:147)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- IssuePin -->
  <testcase name="VerifyPinNoLongerValid" time="4.715" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinOTP&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;188e2f15-bfe6-4266-a55e-3ea609177be6&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinOTP"
     but: was "{"transactionId":"188e2f15-bfe6-4266-a55e-3ea609177be6","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinNoLongerValid(MFAC.java:229)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinNoLongerValid -->
  <testcase name="VerifyPinValid" time="6.266" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;073ffdfb-e1a8-4dba-a9c2-b9e838374690&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"073ffdfb-e1a8-4dba-a9c2-b9e838374690","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinValid(MFAC.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinValid -->
  <testcase name="IssuePin" time="6.665" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinValid" time="7.692" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;457f03e1-281a-4338-906d-362b63b197b5&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"457f03e1-281a-4338-906d-362b63b197b5","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinValid(MFAC.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinValid -->
  <testcase name="VerifyPinVelocity" time="8.837" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;4f73e5ba-8a59-4031-9c8d-54c00a4c3843&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"4f73e5ba-8a59-4031-9c8d-54c00a4c3843","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="VerifyPinNoLongerValid" time="9.989" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinOTP&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;f0075d9f-ec17-4e1b-bebe-fbe4c77a23b1&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinOTP"
     but: was "{"transactionId":"f0075d9f-ec17-4e1b-bebe-fbe4c77a23b1","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinNoLongerValid(MFAC.java:229)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinNoLongerValid -->
  <testcase name="VerifyPinVelocity" time="11.145" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;f241662e-68ee-4fdc-b9df-551ca9c2117a&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"f241662e-68ee-4fdc-b9df-551ca9c2117a","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="IssuePinVelocity" time="17.235" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;pinOTP&amp;quot; and a string containing &amp;quot;pinExpirationDate&amp;quot;)
     but: a string containing &amp;quot;pinOTP&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;3a6d91ce-b228-4889-aecd-00b4cae9e251&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"3a6d91ce-b228-4889-aecd-00b4cae9e251","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:165)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="VerifyPinVelocity" time="19.93" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;78036544-d96d-4be3-97e7-c661fe83f058&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"78036544-d96d-4be3-97e7-c661fe83f058","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="VerifyPinVelocity" time="21.024" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;c6634b42-5654-4227-b86f-b55ebe8dfa3b&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"c6634b42-5654-4227-b86f-b55ebe8dfa3b","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="VerifyPinVelocity" time="23.313" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;cc0718ef-0690-49a3-92fa-e4e81b35d6e1&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"cc0718ef-0690-49a3-92fa-e4e81b35d6e1","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="VerifyPinVelocity" time="24.445" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pinExpirationDate&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;558cc13d-5b86-4c0a-ad0c-7b7de57433d3&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"558cc13d-5b86-4c0a-ad0c-7b7de57433d3","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="IssuePinVelocity" time="26.785" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;pinOTP&amp;quot; and a string containing &amp;quot;pinExpirationDate&amp;quot;)
     but: a string containing &amp;quot;pinOTP&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;d9fb1147-8fa0-4f39-83ea-4315c2fe9b50&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;5700&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"d9fb1147-8fa0-4f39-83ea-4315c2fe9b50","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:165)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="VerifyPinValid" time="28.275" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinValid" time="28.307" classname="MFAC.MFAC"/>
  <testcase name="IssuePinVelocity" time="38.433" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="40.26" classname="MFAC.MFAC"/>
  <testcase name="AddressVelocity" time="40.666" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;ALLOW&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;3dad53b6-0308-46e0-9cc1-7d46afc09c8a&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;DENY&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"3dad53b6-0308-46e0-9cc1-7d46afc09c8a","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="VerifyPinVelocity" time="42.219" classname="MFAC.MFAC"/>
  <testcase name="AddressVelocity" time="42.812" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;ALLOW&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;9c3c6113-9f92-421b-b241-0bb708b38521&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;DENY&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"9c3c6113-9f92-421b-b241-0bb708b38521","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="VerifyPinNoLongerValid" time="43.331" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="43.816" classname="MFAC.MFAC"/>
  <testcase name="AddressVelocity" time="43.996" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;ALLOW&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;0a5047d8-8ce0-49c8-8f46-94aff94ed40b&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;DENY&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"0a5047d8-8ce0-49c8-8f46-94aff94ed40b","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="VerifyPinVelocity" time="44.152" classname="MFAC.MFAC"/>
  <testcase name="IssuePinVelocity" time="44.285" classname="MFAC.MFAC"/>
  <testcase name="AddressVelocity" time="45.605" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;ALLOW&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;ac9565d8-511d-4b2c-b47c-ef8a4e2ec05a&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;DENY&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"ac9565d8-511d-4b2c-b47c-ef8a4e2ec05a","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="VerifyPinNoLongerValid" time="45.704" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="37.521" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="35.334" classname="MFAC.MFAC"/>
</testsuite> <!-- MFAC_Test -->
