<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="TestNG.CMAC" tests="8" failures="4" timestamp="31 Oct 2018 14:38:46 GMT" time="5.931" errors="0">
  <testcase name="CreateProject" time="1.417" classname="TestNG.CMAC"/>
  <testcase name="CreateProject" time="1.432" classname="TestNG.CMAC"/>
  <testcase name="CreateProject" time="1.463" classname="TestNG.CMAC"/>
  <testcase name="CreateProject" time="1.417" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.031" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;orgUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;ce869585-b3ef-4aa5-aa44-3751420efc2b&quot;,&quot;output&quot;:{&quot;projects&quot;:[{&quot;organizationUUID&quot;:&quot;10003&quot;,&quot;applicationUUID&quot;:&quot;1031180938444&quot;,&quot;projectName&quot;:&quot;Proj_Creation4 103118T093844&quot;}]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"ce869585-b3ef-4aa5-aa44-3751420efc2b","output":{"projects":[{"organizationUUID":"10003","applicationUUID":"1031180938444","projectName":"Proj_Creation4 103118T093844"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
  <testcase name="RetrieveProjectDetails" time="0.072" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;orgUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;b124132a-4ce4-4425-a285-2da9a8e8c918&quot;,&quot;output&quot;:{&quot;projects&quot;:[{&quot;organizationUUID&quot;:&quot;10003&quot;,&quot;applicationUUID&quot;:&quot;1031180938443&quot;,&quot;projectName&quot;:&quot;Proj_Creation3 103118T093844&quot;}]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"b124132a-4ce4-4425-a285-2da9a8e8c918","output":{"projects":[{"organizationUUID":"10003","applicationUUID":"1031180938443","projectName":"Proj_Creation3 103118T093844"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
  <testcase name="RetrieveProjectDetails" time="0.031" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;orgUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;7da230fb-9bde-442f-953a-93f3991766b7&quot;,&quot;output&quot;:{&quot;projects&quot;:[{&quot;organizationUUID&quot;:&quot;10003&quot;,&quot;applicationUUID&quot;:&quot;1031180938442&quot;,&quot;projectName&quot;:&quot;Proj_Creation2 103118T093844&quot;}]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"7da230fb-9bde-442f-953a-93f3991766b7","output":{"projects":[{"organizationUUID":"10003","applicationUUID":"1031180938442","projectName":"Proj_Creation2 103118T093844"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
  <testcase name="RetrieveProjectDetails" time="0.068" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;orgUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;2cbed4a4-635e-4639-b99b-b913320624b0&quot;,&quot;output&quot;:{&quot;projects&quot;:[{&quot;organizationUUID&quot;:&quot;10003&quot;,&quot;applicationUUID&quot;:&quot;1031180938441&quot;,&quot;projectName&quot;:&quot;Proj_Creation1 103118T093844&quot;}]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"2cbed4a4-635e-4639-b99b-b913320624b0","output":{"projects":[{"organizationUUID":"10003","applicationUUID":"1031180938441","projectName":"Proj_Creation1 103118T093844"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
</testsuite> <!-- TestNG.CMAC -->
