<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="USRC.USRC_FDM" tests="1" failures="1" timestamp="12 Dec 2018 19:24:24 GMT" time="24.976" errors="0">
  <testcase name="EndtoEndEnrollment" time="24.976" classname="USRC.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;enrollmentOptionsList&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;24e60552-db64-48dc-b9f4-1ac4c1fbde31&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;LOGIN.REAUTHENTICATE.ERROR&quot;,&quot;message&quot;:&quot;We are unable to process your request at the moment.  Please try again later or contact FedEx Customer Service.&quot;,&quot;parameterList&quot;:[]}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "enrollmentOptionsList"
     but: was "{"transactionId":"24e60552-db64-48dc-b9f4-1ac4c1fbde31","errors":[{"code":"LOGIN.REAUTHENTICATE.ERROR","message":"We are unable to process your request at the moment.  Please try again later or contact FedEx Customer Service.","parameterList":[]}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC.USRC_FDM.EndtoEndEnrollment(USRC_FDM.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment -->
</testsuite> <!-- USRC.USRC_FDM -->
