<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="CMAC.CMAC_Resources" tests="18" failures="9" timestamp="01 Nov 2018 02:37:16 GMT" time="25.675" errors="0">
  <testcase name="CreateResource" time="3.732" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="3.788" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="0.168" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="3.514" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="3.676" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="0.300" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="3.628" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="0.452" classname="CMAC.CMAC_Resources"/>
  <testcase name="CreateResource" time="3.568" classname="CMAC.CMAC_Resources"/>
  <testcase name="DeleteResource" time="0.072" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;295b5725-f9db-40ce-b9a9-bf6b2275d33f&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"295b5725-f9db-40ce-b9a9-bf6b2275d33f","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.193" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;2701f01f-47bc-4ed0-9eec-0ecd2c5cae40&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"2701f01f-47bc-4ed0-9eec-0ecd2c5cae40","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.376" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;dfd6db69-eba4-4b67-b20c-4dbe97832e02&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"dfd6db69-eba4-4b67-b20c-4dbe97832e02","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.576" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;5ffa5c6a-a6ee-4f2b-a86c-195fe205f3bb&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"5ffa5c6a-a6ee-4f2b-a86c-195fe205f3bb","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.128" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;e22f0c9e-ae5e-4e36-a208-5f4b5690ba11&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"e22f0c9e-ae5e-4e36-a208-5f4b5690ba11","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.504" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;52735726-8d37-4dad-ae0f-d589d294d33a&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"52735726-8d37-4dad-ae0f-d589d294d33a","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.252" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;44e4f896-80f1-4b1e-8165-0e9a09feba89&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"44e4f896-80f1-4b1e-8165-0e9a09feba89","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.316" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;02fd3b64-c369-4250-ab02-a7e0c2f4124b&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"02fd3b64-c369-4250-ab02-a7e0c2f4124b","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
  <testcase name="DeleteResource" time="0.432" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;9c95ed6b-e163-46e5-831c-cf6cbd321e11&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCES_DONT_EXIST&quot;,&quot;message&quot;:&quot;Unable to delete. Resources with applicationUUID don&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"9c95ed6b-e163-46e5-831c-cf6cbd321e11","errors":[{"code":"RESOURCES_DONT_EXIST","message":"Unable to delete. Resources with applicationUUID don't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.DeleteResource(CMAC_Resources.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteResource -->
</testsuite> <!-- CMAC.CMAC_Resources -->
