<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="CMAC.CMAC_Resources" tests="15" failures="10" timestamp="05 Nov 2018 20:47:58 GMT" time="0.781" errors="0">
  <testcase name="RetrieveResource" time="0.024" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;endpointUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;bd20ae5d-f439-4183-974a-c6cc0bb403f3&quot;,&quot;output&quot;:{&quot;resources&quot;:[]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"bd20ae5d-f439-4183-974a-c6cc0bb403f3","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.RetrieveResource(CMAC_Resources.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="RetrieveResource" time="0.017" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;endpointUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;e8ba2ab4-23ce-45f4-b7e1-edf9884357d7&quot;,&quot;output&quot;:{&quot;resources&quot;:[]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"e8ba2ab4-23ce-45f4-b7e1-edf9884357d7","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.RetrieveResource(CMAC_Resources.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="UpdateResource" time="0.067" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;d69f387d-c5ac-4ab6-934b-64316896ac83&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCE_DOES_NOT_EXIST&quot;,&quot;message&quot;:&quot;Unable to update. Resource with applicationUUID doesn&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"d69f387d-c5ac-4ab6-934b-64316896ac83","errors":[{"code":"RESOURCE_DOES_NOT_EXIST","message":"Unable to update. Resource with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.UpdateResource(CMAC_Resources.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateResource -->
  <testcase name="RetrieveResource" time="0.008" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;endpointUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;ed84751f-8c02-44d8-be1b-235d7c1999cd&quot;,&quot;output&quot;:{&quot;resources&quot;:[]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"ed84751f-8c02-44d8-be1b-235d7c1999cd","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.RetrieveResource(CMAC_Resources.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="UpdateResource" time="0.083" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;6103494e-7cc0-471b-b205-adc8abc84223&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCE_DOES_NOT_EXIST&quot;,&quot;message&quot;:&quot;Unable to update. Resource with applicationUUID doesn&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"6103494e-7cc0-471b-b205-adc8abc84223","errors":[{"code":"RESOURCE_DOES_NOT_EXIST","message":"Unable to update. Resource with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.UpdateResource(CMAC_Resources.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateResource -->
  <testcase name="UpdateResource" time="0.031" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;b895873c-cbe2-4009-b91a-cca4b9ea29bf&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCE_DOES_NOT_EXIST&quot;,&quot;message&quot;:&quot;Unable to update. Resource with applicationUUID doesn&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"b895873c-cbe2-4009-b91a-cca4b9ea29bf","errors":[{"code":"RESOURCE_DOES_NOT_EXIST","message":"Unable to update. Resource with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.UpdateResource(CMAC_Resources.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateResource -->
  <testcase name="UpdateResource" time="0.062" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;c61bbe29-d39b-4e7c-97b1-999927e678df&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCE_DOES_NOT_EXIST&quot;,&quot;message&quot;:&quot;Unable to update. Resource with applicationUUID doesn&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"c61bbe29-d39b-4e7c-97b1-999927e678df","errors":[{"code":"RESOURCE_DOES_NOT_EXIST","message":"Unable to update. Resource with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.UpdateResource(CMAC_Resources.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateResource -->
  <testcase name="RetrieveResource" time="0.059" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;endpointUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;2790d63d-972e-45f4-9fae-772ceda3b8e7&quot;,&quot;output&quot;:{&quot;resources&quot;:[]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"2790d63d-972e-45f4-9fae-772ceda3b8e7","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.RetrieveResource(CMAC_Resources.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="RetrieveResource" time="0.025" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;endpointUUID&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;715add1c-eb1e-4643-89be-ac9f848e68b9&quot;,&quot;output&quot;:{&quot;resources&quot;:[]}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"715add1c-eb1e-4643-89be-ac9f848e68b9","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.RetrieveResource(CMAC_Resources.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="UpdateResource" time="0.031" classname="CMAC.CMAC_Resources">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;output&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;a986716a-2983-4464-9bdd-de6c3761e405&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;RESOURCE_DOES_NOT_EXIST&quot;,&quot;message&quot;:&quot;Unable to update. Resource with applicationUUID doesn&#039;t exist.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "output"
     but: was "{"transactionId":"a986716a-2983-4464-9bdd-de6c3761e405","errors":[{"code":"RESOURCE_DOES_NOT_EXIST","message":"Unable to update. Resource with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CMAC.CMAC_Resources.UpdateResource(CMAC_Resources.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateResource -->
  <testcase name="DeleteResource" time="0.109" classname="CMAC.CMAC_Resources"/>
  <testcase name="DeleteResource" time="0.078" classname="CMAC.CMAC_Resources"/>
  <testcase name="DeleteResource" time="0.031" classname="CMAC.CMAC_Resources"/>
  <testcase name="DeleteResource" time="0.062" classname="CMAC.CMAC_Resources"/>
  <testcase name="DeleteResource" time="0.094" classname="CMAC.CMAC_Resources"/>
</testsuite> <!-- CMAC.CMAC_Resources -->
